# Generated by Django 3.1.4 on 2020-12-09 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=40)),
                ('weeks', models.SmallIntegerField()),
                ('description', models.CharField(max_length=40)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_attached_file', models.FileField(blank=True, upload_to='Emails_Files_Tasks')),
                ('start_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=60)),
                ('mission', models.CharField(max_length=60)),
                ('responsibility', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.BooleanField(choices=[(True, 'open'), (False, 'closed')], default=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.task')),
            ],
        ),
    ]
