# Generated by Django 3.1.3 on 2021-01-20 20:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_auto_20201214_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='weeks',
        ),
        migrations.AddField(
            model_name='task',
            name='days',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
