# Generated by Django 3.1.3 on 2021-02-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_auto_20210120_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'open'), (0, 'closed'), (2, 'stuck')], default=1),
        ),
    ]
